---
title: "Secretary Problem"
author: "Vadim Simonenko"
date: "2023-11-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
n <- 100
simulation_count.grid <- 10^c(2:5)
dist.size <- 10
```



```{r}
optimal_k <- function(n, simulation_count){
  result <- numeric()
  for(k in 1:n){
    result <- c(result, replicate(simulation_count, func() <- {
          secretaries <- runif(n)
          k_max_score <- max(secretaries[1:k])
          winner_score <- secretaries[k+1: n][secretaries[k+1: n] > k_max_score][1]
          max_score <- max(secretaries)
          return(as.numeric(!is.na(winner_score) & winner_score == max_score))
    }) |> mean())
  }
return(which.max(result))
}
```

```{r}
res <- matrix(0, length(simulation_count.grid), dist.size) 

for(s in 1:length(simulation_count.grid)){
  for(j in 1:dist.size){
    res[s, j] <- optimal_k(n, simulation_count.grid[s])
  }
}
```

```{r}
plot(rep(1:length(simulation_count.grid), each = dist.size), as.vector(t(res)),
     xaxt = 'n', xlab = 'simulation count', ylab = 'optimal k')
axis(1, at = 1:length(simulation_count.grid), labels = simulation_count.grid)
abline(h = n/exp(1), col = 'red')
```

